function FK = autogen_fwd_kin(l_pend,r_com_pend,theta_pend,x_cart)
%AUTOGEN_FWD_KIN
%    FK = AUTOGEN_FWD_KIN(L_PEND,R_COM_PEND,THETA_PEND,X_CART)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Apr-2020 22:34:23

t2 = cos(theta_pend);
t3 = sin(theta_pend);
FK = reshape([x_cart,0.0,x_cart+r_com_pend.*t2,r_com_pend.*t3,x_cart+l_pend.*t2,l_pend.*t3],[2,3]);
