function G = autogen_grav_vector(g,m_pend,r_com_pend,theta_pend)
%AUTOGEN_GRAV_VECTOR
%    G = AUTOGEN_GRAV_VECTOR(G,M_PEND,R_COM_PEND,THETA_PEND)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Apr-2020 22:34:26

G = [0.0;g.*m_pend.*r_com_pend.*cos(theta_pend)];
