function C = autogen_coriolis_matrix(b1,b2,dtheta_pend,m_pend,r_com_pend,theta_pend)
%AUTOGEN_CORIOLIS_MATRIX
%    C = AUTOGEN_CORIOLIS_MATRIX(B1,B2,DTHETA_PEND,M_PEND,R_COM_PEND,THETA_PEND)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    12-Apr-2020 22:34:26

C = reshape([b1,0.0,dtheta_pend.*m_pend.*r_com_pend.*cos(theta_pend).*-2.0,b2],[2,2]);
