%% robot_dynamics.m
%
% Description:
%   Computes the right-hand side of the state-space dynamics
%       dx = f_ss(x) + g_ss(x)*u
%
% Inputs:
%   t: time (scalar)
%   x: the state vector, x = [x_cart; theta_pend; dx_cart; dtheta_pend];
%   u: control input (scalar, horizontal force applied to the cart)
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   dx: derivative of state x with respect to time.

function [dx] = robot_dynamics(t,x,u,params)

    f_ss = drift_vector_field(x,params);
    g_ss = control_vector_field(x,params);
    dx = f_ss + g_ss*u;

end